name: pre-release
run-name: ${{ github.actor }} is publishing a pre-release build
on:
  push:
    paths:
      - manifest.json
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          author_name: github.actor
          author_email: github
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install node-jq --save
      - name: "get version_name"
        run: |
          versionName=$(cat manifest.json | jq -r .version_name) && echo $versionName
          echo "next_version_name=${newVersionName}" >> $GITHUB_ENV
      - name: "build the zip"
        run: |
          git archive -o "AboveVTT-${{env.next_version_name}}.zip" HEAD
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{env.next_version_name}}"
          prerelease: true
          title: "${{env.next_version_name}}"
          files: |
            *.zip
            LICENSE
