name: release-build
run-name: ${{ github.actor }} is publishing a pre-release build
on: [workflow_dispatch]
jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          author_name: github.actor
          author_email: github
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install node-jq --save
      - name: "get version"
        run: |
          version=$(cat manifest.json | jq -r .version) && echo version
          echo "next_version_name=${version}" >> $GITHUB_ENV
      - name: "build zip"
        run: |
          git archive -o "AboveVTT-${{env.next_version_name}}.zip" HEAD
      - name: "publish release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{env.next_version_name}}"
          prerelease: ${{ inputs.prerelease }}
          title: "${{env.next_version_name}}"
          files: |
            *.zip
            LICENSE